---
title: "Day 11"
author: "Paige Remde"
date: "2023-12-11"
output: html_document
---

(Day 11)[https://adventofcode.com/2023/day/11]

```{r, message = FALSE, warning = FALSE}

#Part 1----

library(tidyverse)

Day11input <- read.fwf("day11.txt", widths=rep(1,140), comment.char = "", na.strings = "") 

Input_long <- Day11input %>%
  mutate(Row = row_number()) %>%
  pivot_longer(cols = -c(Row), names_to = "Col", values_to = "value")

#create df of rows that have no galaxies
Expand_rows <- Day11input %>%
  mutate(EmptyRow = row_number()) %>%
  filter_all(all_vars(. != "#")) %>%
  select(EmptyRow)

#create df of columns that have no galaxies
Expand_columns <- Day11input %>%
  t() %>%
  as.tibble() %>%
  mutate(EmptyCol = row_number()) %>%
  filter_all(all_vars(. != "#")) %>%
  select(EmptyCol)

Galaxies <- Input_long %>%
  #create IDs for galaxies
  filter(value == "#") %>%
  mutate(ID = row_number()) %>%
  select(ID, Row, Col) %>%
  #make values calculable 
  mutate(across(everything(), str_remove_all, pattern = 'V')) %>%
  mutate(across(everything(), as.numeric)) %>%
  #find how many rows or columns are expanded before each galaxy
  mutate(RowHigher = map_dbl(Row, ~ sum(Expand_rows$EmptyRow < .)),
         ColHigher = map_dbl(Col, ~ sum(Expand_columns$EmptyCol < .))) %>%
  #add number of rows/columns surpassed to original row/column location
  mutate(New_Row = RowHigher + Row,
         New_Col = ColHigher + Col)

Distances <- Galaxies %>%
  #create pairings for galaxies
  expand(Gal1 = ID, Gal2 = ID) %>%
  #get rid of repeats
  filter(Gal1 < Gal2) %>%
  #refer to row and column locations from galaxies df
  mutate(
    Row1 = Galaxies$New_Row[Gal1],
    Col1 = Galaxies$New_Col[Gal1],
    Row2 = Galaxies$New_Row[Gal2],
    Col2 = Galaxies$New_Col[Gal2]) %>%
  #find distance (taxicab distance based on prompt)
  mutate(TCDistance = abs(Row1 - Row2) + abs(Col1 - Col2))

Answer <- sum(Distances$TCDistance)
  
```

(Part 2)[https://adventofcode.com/2023/day/11#part2]

```{r}

#Part2----

#do same thing as part 1 with some changes
Galaxies2 <- Input_long %>%
  filter(value == "#") %>%
  mutate(ID = row_number()) %>%
  select(ID, Row, Col) %>%
  mutate(across(everything(), str_remove_all, pattern = 'V')) %>%
  mutate(across(everything(), as.numeric)) %>%
  mutate(RowHigher = map_dbl(Row, ~ sum(Expand_rows$EmptyRow < .)),
         ColHigher = map_dbl(Col, ~ sum(Expand_columns$EmptyCol < .))) %>%
  #multiply surpassed rows/columns by expansion (-1) and add to original location
  mutate(New_Row = (RowHigher * 999999) + Row,
         New_Col = (ColHigher * 999999) + Col)

Distances2 <- Galaxies2 %>%
  expand(Gal1 = ID, Gal2 = ID) %>%
  filter(Gal1 < Gal2) %>%
  mutate(
    Row1 = Galaxies2$New_Row[Gal1],
    Col1 = Galaxies2$New_Col[Gal1],
    Row2 = Galaxies2$New_Row[Gal2],
    Col2 = Galaxies2$New_Col[Gal2]) %>%
  mutate(TCDistance = abs(Row1 - Row2) + abs(Col1 - Col2))

Answer2 <- sum(Distances2$TCDistance)

```

